application:
  config:
    server: http://localhost:8888
  keycloak:
    server: http://localhost:8085
    realm: master
    clientId: auth
    clientSecret: WV1Ekqdq4LWBnowzxDqCFyl7W8vHci66

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${application.keycloak.server}/realms/${application.keycloak.realm}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    root: DEBUG