application:
  config:
    server: http://localhost:8888
  keycloak:
    server: http://localhost:8085
    realm: master
    clientId: auth
    clientSecret: WV1Ekqdq4LWBnowzxDqCFyl7W8vHci66

spring:
  application:
    name: payment-service
  config:
    import: "configserver:http://localhost:8888"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${application.keycloak.server}/realms/${application.keycloak.realm}
          jwk-set-key: ${application.keycloak.server}/realms/${application.keycloak.realm}/protocol/openid-connect/certs
  logging:
    level: INFO
  output:
    ansi:
      enabled: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

