spring:
  application:
    name: payment-service
  config:
    import: "configserver:http://localhost:8888"
  logging:
    level: INFO
  output:
    ansi:
      enabled: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

