package com.dp.orderservice.persistence.entity;

public enum OrderStatus {
    CALCULATING_COST,
    READY_FOR_PAYMENT,
    PROCESSING_PAYMENT,
    AWAITING_DELIVERY_TO_WAREHOUSE,
    DELIVERED_TO_WAREHOUSE,
    SENT_TO_RECEIVER_COUNTRY,
    ARRIVED_IN_RECEIVER_COUNTRY,
    IN_COUNTRY_TRAVEL,
    DELIVERED_TO_RECEIVER
}
